//= require_self
//= require variables
//= require custom_inputs
//= require charts_init
//= require charts_bar
//= require charts_line
//= require charts_pie
//= require charts_radar
//= require lists
